### ISSUE TITLE
babel6 support?

### ISSUE THREAD

**Issue by Macroz** [4Catalyzer/babel-plugin-dev-expression#1]
Hi!

Noticed today that babel-plugin-dev-expression works with babel 5.4.7
but can't use it with babel 6.3.13.
```
TypeError: t.literal is not a function
    at module.exports (/.../node_modules/babel-plugin-dev-expression/dev-expression.js:26:7)
```

**Comment by taion** [comment]
This is just taken from https://github.com/facebook/fbjs/blob/master/scripts/babel/dev-expression.js. I don't plan on adding Babel 6 support before Facebook themselves do.

**Comment by oliviertassinari** [comment]
I wish we had this feature. Looks like this is preventing react-router to update to babel v6.
https://github.com/rackt/react-router/blob/master/.babelrc.

**Comment by taion** [comment]
I didn't write this plugin. This is strictly a mirror of the fbjs upstream. There's nothing I'm going to do about this.

Also, this isn't what's keeping React Router from updating to Babel 6, either.

**Comment by oliviertassinari** [comment]
> Also, this isn't what's keeping React Router from updating to Babel 6, either.

Alright, I'm gonna wait to see the solution they came up with.
Thanks anyway.

**Comment by taion** [comment]
We're not going to do anything on the React Router side in the near term. There's too much other stuff we need to do first that's higher priority than moving from Babel 5 to Babel 6.

**Comment by oliviertassinari** [comment]
If this can help, I ended up creating my own plugin https://github.com/oliviertassinari/babel-plugin-transform-dev-warning for https://github.com/callemall/material-ui/pull/2620.

**Comment by taion** [comment]
Babel 6 is now supported on v0.2.x – I pulled in the changes from fbjs upstream.
